### ISSUE TITLE
Compatibility issue with latest R: 4.5.0

### ISSUE THREAD

**Issue by DanielleCass** [ismayc/chemistr#1]
When R is updated to R 4.5.0 the chemistr package would not install (and library would not load) into RStudio (desktop) 1.1.453.
![screen shot 2018-05-29 at 3 40 27 pm](https://user-images.githubusercontent.com/29213205/40689358-a46041ac-6356-11e8-829f-b87e23cec4df.png)

**Comment by vestoj** [comment]
To install the package, you should use `devtools::install_github("ismayc/chemistr")`
